@base = http://localhost:8080


#### Login
# @name login 
POST {{base}}/api/auth/signin
Content-Type: application/json

{
    "username" : "admin",
    "password" : "password"
}

#### Create a new Schema
POST {{base}}/api/schema
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "$id": "product",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "A product from Acme's catalog",
  "title": "Product",
  "label": "title",
  "type": "object",
  "properties": {
    "id": {
      "description": "The unique identifier for a product",
      "type": "integer",
      "title": "Id"
    },
    "title": {
      "description": "Name of the product",
      "type": "string",
      "title": "Title"
    },
    "price": {
      "description": "The price for a product",
      "type": "number",
      "title": "Price"
    },
    "availablity": {
      "description": "The availablity for a product",
      "type": "boolean",
      "title": "is Available"
    }
  },
  "required": [
    "id"
  ],
  "ids": [
    "id"
  ]
}


#### Create a new product
POST {{base}}/api/data/product
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

{
  "id": 2,
  "title" : "Zols",
  "price" : 100000000.50,
  "availablity" : true
}



#### List all products
GET {{base}}/api/data/product
Authorization: Bearer {{login.response.body.accessToken}}
Content-Type: application/json

