/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.zols.datastore.elasticsearch;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.Map;
import org.elasticsearch.action.admin.indices.create.CreateIndexRequest;
import org.elasticsearch.action.admin.indices.delete.DeleteIndexRequest;
import org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest;
import org.elasticsearch.action.admin.indices.refresh.RefreshRequest;
import org.elasticsearch.action.delete.DeleteResponse;
import org.elasticsearch.action.get.GetResponse;
import org.elasticsearch.action.index.IndexRequestBuilder;
import org.elasticsearch.action.index.IndexResponse;
import org.elasticsearch.action.search.SearchResponse;
import org.elasticsearch.client.Client;
import org.elasticsearch.common.settings.Settings;
import static org.elasticsearch.common.settings.Settings.settingsBuilder;
import org.elasticsearch.index.query.BoolQueryBuilder;
import org.elasticsearch.index.query.QueryBuilder;
import org.elasticsearch.index.query.QueryBuilders;
import static org.elasticsearch.node.NodeBuilder.nodeBuilder;
import org.elasticsearch.search.SearchHit;
import org.elasticsearch.search.SearchHits;

import static org.slf4j.LoggerFactory.getLogger;
import org.zols.datastore.DataStore;
import org.zols.datastore.jsonschema.JSONSchema;
import org.zols.datastore.query.Filter;
import static org.zols.datastore.query.Filter.Operator.EQUALS;
import org.zols.datastore.query.Query;
import org.zols.datatore.exception.DataStoreException;

/**
 *
 * Elastic Search Implementation of DataStore
 *
 * @author Raji
 */
public class ElasticSearchDataStore extends DataStore {

    private static final org.slf4j.Logger LOGGER = getLogger(ElasticSearchDataStore.class);

    private final Client client;

    private final String indexName;

    public ElasticSearchDataStore() {
        this.indexName = "zols";
        Settings settings = settingsBuilder().put("index.number_of_shards", 1)
                .put("path.home", "/")
                .put("path.data", "data")
                .put("index.number_of_replicas", 0).build();
        client = nodeBuilder().settings(settings).local(true).build().start().client();
        createIndexIfNotExists();
    }

    public ElasticSearchDataStore(String indexName) {
        this.indexName = indexName;
        Settings settings = settingsBuilder().put("index.number_of_shards", 1)
                .put("path.home", "/")
                .put("path.data", "data")
                .put("index.number_of_replicas", 0).build();
        client = nodeBuilder().settings(settings).local(true).build().start().client();
        createIndexIfNotExists();
    }

    public ElasticSearchDataStore(String indexName, Client client) {
        this.indexName = indexName;
        this.client = client;
        createIndexIfNotExists();
    }

    private void patchDelayInRefresh() {
//        try {
//            Thread.sleep(300);
//        } catch (InterruptedException ex) {
//            Logger.getLogger(ElasticSearchDataStore.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private void createIndexIfNotExists() {
        IndicesExistsRequest indicesExistsRequest = new IndicesExistsRequest(indexName);
        if (!client.admin().indices().exists(indicesExistsRequest).actionGet().isExists()) {
            CreateIndexRequest createIndexRequest = new CreateIndexRequest(indexName);
            client.admin().indices().create(createIndexRequest).actionGet();
            LOGGER.debug("New index [{}] created", indexName);
        }
    }

    @Override
    protected Map<String, Object> create(JSONSchema jsonSchema, Map<String, Object> validatedDataObject) {
        LOGGER.debug("Create Data for ", jsonSchema.id());
        Object idValue = validatedDataObject.get(jsonSchema.idField());
        IndexRequestBuilder indexRequestBuilder;
        if (idValue == null) {
            indexRequestBuilder = client.prepareIndex(indexName, jsonSchema.id()).setRefresh(true);
        } else {
            indexRequestBuilder = client.prepareIndex(indexName, jsonSchema.id(), idValue.toString()).setRefresh(true);
        }

        IndexResponse response = indexRequestBuilder
                .setSource(validatedDataObject)
                .execute()
                .actionGet();

        Map<String, Object> createdData = null;

        if (response.isCreated()) {
            createdData = read(jsonSchema, response.getId());
            //If autogenerated if then update idField
            if (idValue == null) {
                createdData.put(jsonSchema.idField(), response.getId());
                update(jsonSchema, createdData);
            }
        }

        patchDelayInRefresh();
        return createdData;

    }

    @Override
    protected Map<String, Object> read(JSONSchema jsonSchema, String idValue) {
        GetResponse getResponse = client
                .prepareGet(indexName, jsonSchema.id(), idValue)
                .execute()
                .actionGet();
        patchDelayInRefresh();
        return getResponse.getSource();
    }

    @Override
    protected boolean delete(JSONSchema jsonSchema) {
        List<Map<String, Object>> list = list(jsonSchema);
        list.stream().forEach(dataMap -> delete(jsonSchema, dataMap.get(jsonSchema.idField()).toString()));
        client.admin().indices().refresh(new RefreshRequest(indexName));
        patchDelayInRefresh();
        return true;
    }

    @Override
    protected boolean delete(JSONSchema jsonSchema, String idValue) {
        DeleteResponse response = client
                .prepareDelete(indexName, jsonSchema.id(), idValue).setRefresh(true)
                .execute()
                .actionGet();
        client.admin().indices().refresh(new RefreshRequest(indexName));
        patchDelayInRefresh();
        return response.isFound();
    }

    @Override
    protected boolean delete(JSONSchema jsonSchema, Query query) {
        List<Map<String, Object>> list = list(jsonSchema, query);
        list.stream().forEach(dataMap -> delete(jsonSchema, dataMap.get(jsonSchema.idField()).toString()));
        client.admin().indices().refresh(new RefreshRequest(indexName));
        patchDelayInRefresh();
        return true;
    }

    @Override
    protected boolean update(JSONSchema jsonSchema, Map<String, Object> validatedDataObject) {
        String idValue = validatedDataObject.get(jsonSchema.idField()).toString();
        IndexResponse response = client.prepareIndex(indexName, jsonSchema.id(), idValue).setRefresh(true)
                .setSource(validatedDataObject)
                .execute()
                .actionGet();
        client.admin().indices().refresh(new RefreshRequest(indexName));
        patchDelayInRefresh();
        return response.isCreated();
    }

    @Override
    protected List<Map<String, Object>> list(JSONSchema jsonSchema) {
        List<Map<String, Object>> list = null;
        SearchResponse response = client
                .prepareSearch()
                .setIndices(indexName)
                .setTypes(jsonSchema.id())
                .execute().actionGet();
        SearchHits hits = response.getHits();
        if (hits != null) {
            SearchHit[] searchHits = hits.getHits();
            if (searchHits != null) {
                list = new ArrayList<>(searchHits.length);
                for (SearchHit searchHit : searchHits) {
                    list.add(searchHit.getSource());
                }
            }
        }
        return list;
    }

    @Override
    protected List<Map<String, Object>> list(JSONSchema jsonSchema, Query query) {
        List<Map<String, Object>> list = null;
        SearchResponse response = client
                .prepareSearch()
                .setIndices(indexName)
                .setTypes(jsonSchema.id())
                .setQuery(getQueryBuilder(query))
                .execute().actionGet();
        SearchHits hits = response.getHits();
        if (hits != null) {
            SearchHit[] searchHits = hits.getHits();
            if (searchHits != null) {
                list = new ArrayList<>(searchHits.length);
                for (SearchHit searchHit : searchHits) {
                    list.add(searchHit.getSource());
                }
            }
        }
        return list;
    }

    @Override
    protected void drop() throws DataStoreException {
        client.admin().indices().delete(new DeleteIndexRequest(indexName));
    }

    private QueryBuilder getQueryBuilder(Query query) {
        BoolQueryBuilder queryBuilder = QueryBuilders.boolQuery();
        if (query != null) {
            List<Filter> queries = query.getFilters();
            if (queries != null) {
                int size = queries.size();
                Filter filter;
                for (int index = 0; index < size; index++) {
                    filter = queries.get(index);
                    switch (filter.getOperator()) {
                        case EQUALS:
                            queryBuilder.must(QueryBuilders.matchQuery(filter.getName(), filter.getValue()));
                            break;
                        case IS_NULL:
                            queryBuilder.mustNot(QueryBuilders.existsQuery(filter.getName()));
                            break;
                        case IS_NOTNULL:
                            queryBuilder.must(QueryBuilders.existsQuery(filter.getName()));
                            break;
                        case EXISTS_IN:         
                            Collection collection = (Collection) filter.getValue();
                            for (Object object : collection) {
                                queryBuilder.should(QueryBuilders.matchQuery(filter.getName(), object));
                            }
                            
                            break;
                    }
                }
            }
        }        
        return queryBuilder;
    }

}
