name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build with npm
        run: |
          export BUILD_PRODUCTION=Y
          cd zols-ui
          npm install
          mkdir ../zols-web/src/main/resources/static
          cp -rf dist/** ../zols-web/src/main/resources/static/
          ls ../zols-web/src/main/resources/static
        env:
          CI: true
      - name: Build with Maven
        run: docker run -d --rm -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:7.16.2 && mvn -B clean package --file pom.xml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./zols-web/target/zols-web-1.0-SNAPSHOT.jar
          asset_name: zols-web-1.0-SNAPSHOT.jar
          asset_content_type: application/jar
#    - name: Deploy UI
#      uses: appleboy/scp-action@master
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        key: ${{ secrets.KEY }}
#        passphrase: ${{ secrets.PASSPHRASE }}
#        source: zols-ui/dist
#        target: ${{ secrets.STATIC_DIR }}
#        strip_components: 2